"""ajout des stripe_price_id

Revision ID: 1af559b3b79f
Revises: 3e92a89386d9
Create Date: 2024-10-15 12:50:34.271262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af559b3b79f'
down_revision = '3e92a89386d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('price_id')

    # ### end Alembic commands ###
