"""suppression de la colone type danss la table offer

Revision ID: 880c7c640cfb
Revises: c6454d855089
Create Date: 2024-10-11 16:02:06.118113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '880c7c640cfb'
down_revision = 'c6454d855089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.ENUM('solo', 'duo', 'familiale'), nullable=False))

    # ### end Alembic commands ###
