"""ajout des stripe_price_id

Revision ID: e7fa73d3c36f
Revises: 1af559b3b79f
Create Date: 2024-10-15 12:52:34.465053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7fa73d3c36f'
down_revision = '1af559b3b79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=64), nullable=False))
        batch_op.drop_column('price_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('stripe_price_id')

    # ### end Alembic commands ###
